server:
  port: 8080

spring:
  application:
    name: jsbt0
  grpc:
    server:
      port: 9090

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: jsbt0
    description: Java Spring Boot Template Project Zero
